name: libclang-windows-amd64

on:
  push:
  workflow_dispatch:
    inputs:
      git_tag:
        description: 'Git tag to checkout'
        required: true

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: llvmorg-19.1.6
#        ref: ${{ github.event.inputs.git_tag }}
    - name: Setup the Build
      run: |
        mkdir --parents build && cd build/
        cmake ../llvm \
          -G "Visual Studio 17 2022" \
          -A x64 \
          -Thost=x64 \
          -DCMAKE_BUILD_TYPE=Release \
          -DLLVM_ENABLE_PROJECTS=clang \
          -DBUILD_SHARED_LIBS=OFF \
          -DLLVM_ENABLE_ZLIB=OFF \
          -DLLVM_ENABLE_ZSTD=OFF \
          -DLLVM_TARGETS_TO_BUILD=X86 \
          -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded
          #-DLLVM_USE_CRT_MINSIZEREL="MT"
    - name: Build
      run: cd build/ && cmake --build . --config Release --parallel --target libclang
    - name: Prepare the built artifact
      run: |
        VERSION_SUFFIX=
        if [[ -n "${{ github.event.inputs.git_tag }}" ]]; then
            VERSION_SUFFIX="${{ github.event.inputs.git_tag }}"
            VERSION_SUFFIX="${VERSION_SUFFIX#llvmorg-}"
        fi
        mkdir --parents build/staging/
        cd build/
        cp Release/bin/libclang.* Release/lib/libclang.* staging/
        cd staging/
        sha512sum libclang.dll > libclang.dll${VERSION_SUFFIX}.windows-amd64.sha512sum
        echo "Checksum is: $(cut --delimiter=' ' --fields=1 libclang.dll${VERSION_SUFFIX}.windows-amd64.sha512sum)"
        #tar -zcvf ../libclang.dll${VERSION_SUFFIX}.windows-amd64.tgz *.*
        #sha512sum ../libclang.dll${VERSION_SUFFIX}.windows-amd64.tgz
    - name: "List everything (for debugging/reference)"
      run: ls -lahR build/
    - uses: actions/upload-artifact@v4
      with:
        name: libclang.dll.windows-amd64
        path: build/staging/libclang.*
        compression-level: 9
