name: libclang-windows-amd64

on:
  push:
  workflow_dispatch:
    inputs:
      git_tag:
        description: 'Git tag to checkout'
        required: true

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: llvmorg-19.1.6
#        ref: ${{ github.event.inputs.git_tag }}
    - name: make build directory
      run: |
        mkdir --parents build
        mkdir --parents build/RelWithDebInfo/bin
    - name: test tools
      run: |
        set -x
        VERSION_SUFFIX=
        if [[ -n "${{ github.event.inputs.git_tag }}" ]]; then
            VERSION_SUFFIX="${{ github.event.inputs.git_tag }}"
            VERSION_SUFFIX="${VERSION_SUFFIX#llvmorg-}"
        fi
        cd build/RelWithDebInfo/bin/
        echo -n "1234" > libclang.dll
        sha512sum libclang.dll > libclang.dll${VERSION_SUFFIX}.windows-amd64.sha512sum
        echo "Checksum is: $(cut --delimiter=' ' --fields=1 libclang.dll${VERSION_SUFFIX}.windows-amd64.sha512sum)"
        tar zcvf libclang.dll${VERSION_SUFFIX}.windows-amd64.tar.gz libclang.dll libclang.dll${VERSION_SUFFIX}.windows-amd64.sha512sum
        sha512sum libclang.dll${VERSION_SUFFIX}.windows-amd64.tar.gz
    - name: cmake
      run: |
        set -x
        cd build/
        pwd
        cmake ../llvm \
          -G "Visual Studio 17 2022" \
          -A x64 \
          -Thost=x64 \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DLLVM_ENABLE_PROJECTS=clang \
          -DBUILD_SHARED_LIBS=OFF \
          -DLLVM_ENABLE_ZLIB=OFF \
          -DLLVM_ENABLE_ZSTD=OFF \
          -DLLVM_ENABLE_TERMINFO=OFF \
          -DLLVM_TARGETS_TO_BUILD=X86 \
          -DLLVM_USE_CRT_MINSIZEREL="MT"
          #-DCMAKE_CXX_FLAGS="/MP" \
#    - name: build
#      run: cd build && cmake --build . --config RelWithDebInfo --target libclang
#    - name: create and print sha512sum
#      run: |
#        $env:Path = "C:\Program Files\Git\usr\bin;$env:Path"
#        cd build\RelWithDebInfo\bin
#        sha512sum.exe libclang.dll > libclang.dll.windows-amd64.sha512sum
#        echo "Checksum is: "
#        Get-Content -Path libclang.dll.windows-amd64.sha512sum
#        tar zcvf libclang.dll.windows-amd64.tar.gz libclang.dll libclang.dll.windows-amd64.sha512sum
#        sha512sum.exe libclang.dll.windows-amd64.tar.gz
    - name: test files
      run: |
        set -x
        echo "Current directory"
        pwd
        ls build/
        ls build/RelWithDebInfo/
        ls build/RelWithDebInfo/bin/
    - uses: actions/upload-artifact@v4
      with:
        name: libclang.dll.windows-amd64.tar.gz
        path: build/RelWithDebInfo/bin/libclang.dll.*.tar.gz
